(ns advenjure.text.es-past)

(def dictionary
  {"\nThe End." "\nFin.",
   "\nThere was %s there." "\nHabía %s acá.",
   "%s %s with what?" "%s %s con qué?",
   "%s contained % and %" "%s contenía % y %",
   "%s contained %s" "%s contenía %s",
   "%s contained:%s" "%s contenía:%s",
   "%s was closed." "%s estaba cerrado.", ;FIXME gender
   "%s was empty." "%s estaba vacío.", ;FIXME gender
   "%s what?" "%s qué?",
   "Bye!" "Chau!",
   "Closed." "Hecho.", ;FIXME gender
   "Couldn't go in that direction" "No podía ir en esa dirección",
   "Done." "Hecho.",
   "I already had that." "Ya tenía eso.",
   "I couldn't %s that." "No podía %s eso.",
   "I couldn't look inside a %s." "No podía mirar dentro de eso.",
   "I didn't know how to do that." "No sabía cómo hacer eso.",
   "I didn't see that." "No veía eso.",
   "I was carrying:" "Llevaba:",
   "I was standing up already" "Ya estaba levantado.",
   "I wasn't carrying anything." "No llevaba nada encima.",
   "It was already closed." "Ya estaba cerrado.", ;FIXME gender
   "It was already open." "Ya estaba abierto.", ;FIXME gender
   "It was locked." "Estaba trabado con llave.", ;FIXME gender
   "It wasn't locked." "No está trabado con llave.", ;FIXME gender
   "No saved game found." "No se encotró un juego guardado.",
   "Opened." "Abierto.",
   "Taken." "Hecho.",
   "That didn't work." "Eso no funcionaba.",
   "The %s" "El %s", ;FIXME gender
   "There was nothing special about it." "No tenía nada de especial.",
   "Unlocked." "Hecho.",
   "Which %s?" "Cuál %s?",
   "^close$" "^cerrar$",
   "^describe (?<item2>.*)" "^describir (?<item2>.*)",
   "^describe$" "^describir$",
   "^get (?<item2>.*)" "^tomar (?<item2>.*)",
   "^get$" "^tomar$",
   "^go$" "^ir$",
   "^i$" "^i$",
   "^l$" "^mirar$",
   "^load$" "^cargar$",
   "^look around$" "^mirar alrededor$",
   "^look at$" "^mirar a$",
   "^look in$" "^mirar en$",
   "^look inside (?<item2>.*)" "^mirar dentro de (?<item2>.*)",
   "^look inside$" "^mirar dentro de$",
   "^m$" "^m$",
   "^open (?<item1>.*) with (?<item2>.*)" "^abrir (?<item1>.*) con (?<item2>.*)",
   "^open (?<item>.*) with" "^abrir (?<item>.*) con",
   "^open$" "^abrir$",
   "^pick (?<item1>.*)" "^agarrar (?<item1>.*)",
   "^pick (?<item>.*) up$" "^agarrar (?<item>.*) up$",
   "^pick up (?<item2>.*)" "^agarrar (?<item2>.*)",
   "^pick up$" "^agarrar$",
   "^pick$" "^agarrar$",
   "^read$" "^leer$",
   "^stand up$" "^levantarse$",
   "^stand$" "^levantar$",
   "^take$" "^tomar$",
   "^talk (?<item>.*)" "^hablar (?<item>.*)",
   "^talk to (?<item>.*)" "^hablar con (?<item>.*)",
   "^unlock (?<item1>.*) with$" "^destrabar (?<item1>.*) con$",
   "^unlock (?<item>.*)" "^destrabar (?<item>.*)",
   "^unlock$" "^destrabar$",
   "a " "un "}) ;FIXME gender ;FIXME should be handled at the english dict
